repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: forbid-new-submodules
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: no-commit-to-branch  # blocks main commits.  To bypass do git commit --allow-empty
  - id: pretty-format-json
